### ISSUE TITLE
Issue that happend when we edit a new mockup for the first time

### ISSUE THREAD

**Issue by kapit4n** [kapit4n/mockupero-ui#38]
Steps:
Create a project with user1
Share to user2
Create a new mockup with user2
Edit the new mockup with user2 and save it
This error is shown after we try to save the mockup
 {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"http://localhost:1337/mockupVersion","params":{"where":{"mockup":"582e476bbcee1dd820f9fb88"},"sort":"createdAt DESC"},"headers":{"Accept":"application/json, text/plain, */*"},"withCredentials":true},"statusText":""}

**Comment by kapit4n** [comment]
more info
error: Unable to parse HTTP body- error occurred :: 'Error (E_UNKNOWN) :: Encountered an unexpected error\nMongoError: server localhost:27017 sockets closed\n  at Server.destroy (/home/llll/projects/mockupero-api/node_modules/mongodb-core/lib/topologies/server.js:679:47)\n  at Server.close (/home/llll/projects/mockupero-api/node_modules/mongodb/lib/server.js:372:17)\n  at Db.close (/home/llll/projects/mockupero-api/node_modules/mongodb/lib/db.js:334:19)\n  at /home/llll/projects/mockupero-api/node_modules/sails-mongo/lib/adapter.js:145:14\n  at /home/llll/projects/mockupero-api/node_modules/async/lib/async.js:181:20\n  at Object.async.forEachOf.async.eachOf (/home/llll/projects/mockupero-api/node_modules/async/lib/async.js:233:13)\n  at Object.async.forEach.async.each (/home/llll/projects/mockupero-api/node_modules/async/lib/async.js:209:22)\n  at Object.teardown (/home/llll/projects/mockupero-api/node_modules/sails-mongo/lib/adapter.js:143:22)\n  at /home/llll/projects/mockupero-api/node_modules/sails/lib/hooks/orm/index.js:244:19\n  at /home/llll/projects/mockupero-api/node_modules/sails/node_modules/async/lib/async.js:122:13\n  at _each (/home/llll/projects/mockupero-api/node_modules/sails/node_modules/async/lib/async.js:46:13)\n  at Object.async.each (/home/llll/projects/mockupero-api/node_modules/sails/node_modules/async/lib/async.js:121:9)\n  at Sails.teardown (/home/llll/projects/mockupero-api/node_modules/sails/lib/hooks/orm/index.js:241:13)\n  at Sails.g (events.js:291:16)\n  at emitNone (events.js:91:20)\n  at Sails.emit (events.js:185:7)\n  at Sails.emitter.emit (/home/llll/projects/mockupero-api/node_modules/sails/lib/app/private/after.js:50:11)\n  at /home/llll/projects/mockupero-api/node_modules/sails/lib/app/lower.js:60:11\n  at beforeShutdown (/home/llll/projects/mockupero-api/node_modules/sails/lib/app/lower.js:35:12)\n  at Sails.lower (/home/llll/projects/mockupero-api/node_modules/sails/lib/app/lower.js:39:3)\n  at Sails.bound (/home/llll/projects/mockupero-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)\n  at process.<anonymous> (/home/llll/projects/mockupero-api/node_modules/sails/lib/app/private/initialize.js:44:32)\n  at emitOne (events.js:96:13)\n  at process.emit (events.js:188:7)\n  at process._fatalException (bootstrap_node.js:304:21)\n'
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'assets/images/582fcefff21a155618345ded.png'
  at Error (native)
